/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { licensesControllerV1Deactivate } from "../../funcs/licensesControllerV1Deactivate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.LicensesControllerV1DeactivateRequest$inboundSchema,
};

export const tool$licensesControllerV1Deactivate: ToolDefinition<typeof args> =
  {
    name: "licenses-controller-v1-deactivate",
    description: `Deactivate a license key instance.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await licensesControllerV1Deactivate(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
