/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { checkoutsControllerV1CreateCheckout } from "../../funcs/checkoutsControllerV1CreateCheckout.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CheckoutsControllerV1CreateCheckoutRequest$inboundSchema,
};

export const tool$checkoutsControllerV1CreateCheckout: ToolDefinition<
  typeof args
> = {
  name: "checkouts-controller-v1-create-checkout",
  description: `Creates a new checkout session.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await checkoutsControllerV1CreateCheckout(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
