/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersControllerV1Retrieve } from "../../funcs/customersControllerV1Retrieve.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CustomersControllerV1RetrieveRequest$inboundSchema,
};

export const tool$customersControllerV1Retrieve: ToolDefinition<typeof args> = {
  name: "customers-controller-v1-retrieve",
  description: `Retrieve a customer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersControllerV1Retrieve(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
