/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerPortalGenerateLogin } from "../../funcs/customerPortalGenerateLogin.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CustomerPortalGenerateLoginRequest$inboundSchema,
};

export const tool$customerPortalGenerateLogin: ToolDefinition<typeof args> = {
  name: "customer-portal-generate-login",
  description: `Generate Customer Links`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerPortalGenerateLogin(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
