/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersBillingControllerV1Generate } from "../../funcs/customersBillingControllerV1Generate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CustomersBillingControllerV1GenerateRequest$inboundSchema,
};

export const tool$customersBillingControllerV1Generate: ToolDefinition<
  typeof args
> = {
  name: "customers-billing-controller-v1-generate",
  description: `Generate Customer Links`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersBillingControllerV1Generate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
