/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { discountsControllerV1Create } from "../../funcs/discountsControllerV1Create.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DiscountsControllerV1CreateRequest$inboundSchema,
};

export const tool$discountsControllerV1Create: ToolDefinition<typeof args> = {
  name: "discounts-controller-v1-create",
  description: `Create a discount.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await discountsControllerV1Create(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
