/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getCustomer } from "../../funcs/getCustomer.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetCustomerRequest$inboundSchema,
};

export const tool$getCustomer: ToolDefinition<typeof args> = {
  name: "get-customer",
  description: `Retrieve a customer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
