/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { licensesControllerV1Activate } from "../../funcs/licensesControllerV1Activate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.LicensesControllerV1ActivateRequest$inboundSchema,
};

export const tool$licensesControllerV1Activate: ToolDefinition<typeof args> = {
  name: "licenses-controller-v1-activate",
  description: `Activates a license key.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await licensesControllerV1Activate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
