/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { licensesControllerV1Validate } from "../../funcs/licensesControllerV1Validate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.LicensesControllerV1ValidateRequest$inboundSchema,
};

export const tool$licensesControllerV1Validate: ToolDefinition<typeof args> = {
  name: "licenses-controller-v1-validate",
  description: `Validates a license key or instance.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await licensesControllerV1Validate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
