/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { productsControllerV1Create } from "../../funcs/productsControllerV1Create.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ProductsControllerV1CreateRequest$inboundSchema,
};

export const tool$productsControllerV1Create: ToolDefinition<typeof args> = {
  name: "products-controller-v1-create",
  description: `Creates a new product.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await productsControllerV1Create(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
