/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsControllerV1Cancel } from "../../funcs/subscriptionsControllerV1Cancel.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SubscriptionsControllerV1CancelRequest$inboundSchema,
};

export const tool$subscriptionsControllerV1Cancel: ToolDefinition<typeof args> =
  {
    name: "subscriptions-controller-v1-cancel",
    description: `Cancel a subscription.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await subscriptionsControllerV1Cancel(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
