/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsControllerV1Retrieve } from "../../funcs/subscriptionsControllerV1Retrieve.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SubscriptionsControllerV1RetrieveRequest$inboundSchema,
};

export const tool$subscriptionsControllerV1Retrieve: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-controller-v1-retrieve",
  description: `Retrieve a subscription`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsControllerV1Retrieve(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
