/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsControllerV1Search } from "../../funcs/transactionsControllerV1Search.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TransactionsControllerV1SearchRequest$inboundSchema,
};

export const tool$transactionsControllerV1Search: ToolDefinition<typeof args> =
  {
    name: "transactions-controller-v1-search",
    description: `List all transactions`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await transactionsControllerV1Search(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
