/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { CreemCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$checkoutsControllerV1Retrieve } from "./tools/checkoutsControllerV1Retrieve.js";
import { tool$createCheckout } from "./tools/createCheckout.js";
import { tool$customersBillingControllerV1Generate } from "./tools/customersBillingControllerV1Generate.js";
import { tool$customersControllerV1Retrieve } from "./tools/customersControllerV1Retrieve.js";
import { tool$discountsControllerV1Create } from "./tools/discountsControllerV1Create.js";
import { tool$discountsControllerV1Delete } from "./tools/discountsControllerV1Delete.js";
import { tool$discountsControllerV1Retrieve } from "./tools/discountsControllerV1Retrieve.js";
import { tool$licensesControllerV1Activate } from "./tools/licensesControllerV1Activate.js";
import { tool$licensesControllerV1Deactivate } from "./tools/licensesControllerV1Deactivate.js";
import { tool$licensesControllerV1Validate } from "./tools/licensesControllerV1Validate.js";
import { tool$productsControllerV1Create } from "./tools/productsControllerV1Create.js";
import { tool$productsControllerV1Retrieve } from "./tools/productsControllerV1Retrieve.js";
import { tool$productsControllerV1Search } from "./tools/productsControllerV1Search.js";
import { tool$subscriptionsControllerV1Cancel } from "./tools/subscriptionsControllerV1Cancel.js";
import { tool$subscriptionsControllerV1Retrieve } from "./tools/subscriptionsControllerV1Retrieve.js";
import { tool$subscriptionsControllerV1Update } from "./tools/subscriptionsControllerV1Update.js";
import { tool$subscriptionsControllerV1Upgrade } from "./tools/subscriptionsControllerV1Upgrade.js";
import { tool$transactionsControllerV1Search } from "./tools/transactionsControllerV1Search.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Creem",
    version: "0.3.0",
  });

  const client = new CreemCore({
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$productsControllerV1Retrieve);
  tool(tool$productsControllerV1Create);
  tool(tool$productsControllerV1Search);
  tool(tool$customersControllerV1Retrieve);
  tool(tool$customersBillingControllerV1Generate);
  tool(tool$subscriptionsControllerV1Retrieve);
  tool(tool$subscriptionsControllerV1Cancel);
  tool(tool$subscriptionsControllerV1Update);
  tool(tool$subscriptionsControllerV1Upgrade);
  tool(tool$checkoutsControllerV1Retrieve);
  tool(tool$createCheckout);
  tool(tool$licensesControllerV1Activate);
  tool(tool$licensesControllerV1Deactivate);
  tool(tool$licensesControllerV1Validate);
  tool(tool$discountsControllerV1Retrieve);
  tool(tool$discountsControllerV1Create);
  tool(tool$discountsControllerV1Delete);
  tool(tool$transactionsControllerV1Search);

  return server;
}
