/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CheckoutsControllerV1RetrieveRequest = {
  checkoutId: string;
  xApiKey: string;
};

/** @internal */
export const CheckoutsControllerV1RetrieveRequest$inboundSchema: z.ZodType<
  CheckoutsControllerV1RetrieveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  checkout_id: z.string(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "checkout_id": "checkoutId",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type CheckoutsControllerV1RetrieveRequest$Outbound = {
  checkout_id: string;
  "x-api-key": string;
};

/** @internal */
export const CheckoutsControllerV1RetrieveRequest$outboundSchema: z.ZodType<
  CheckoutsControllerV1RetrieveRequest$Outbound,
  z.ZodTypeDef,
  CheckoutsControllerV1RetrieveRequest
> = z.object({
  checkoutId: z.string(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    checkoutId: "checkout_id",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutsControllerV1RetrieveRequest$ {
  /** @deprecated use `CheckoutsControllerV1RetrieveRequest$inboundSchema` instead. */
  export const inboundSchema =
    CheckoutsControllerV1RetrieveRequest$inboundSchema;
  /** @deprecated use `CheckoutsControllerV1RetrieveRequest$outboundSchema` instead. */
  export const outboundSchema =
    CheckoutsControllerV1RetrieveRequest$outboundSchema;
  /** @deprecated use `CheckoutsControllerV1RetrieveRequest$Outbound` instead. */
  export type Outbound = CheckoutsControllerV1RetrieveRequest$Outbound;
}

export function checkoutsControllerV1RetrieveRequestToJSON(
  checkoutsControllerV1RetrieveRequest: CheckoutsControllerV1RetrieveRequest,
): string {
  return JSON.stringify(
    CheckoutsControllerV1RetrieveRequest$outboundSchema.parse(
      checkoutsControllerV1RetrieveRequest,
    ),
  );
}

export function checkoutsControllerV1RetrieveRequestFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutsControllerV1RetrieveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CheckoutsControllerV1RetrieveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutsControllerV1RetrieveRequest' from JSON`,
  );
}
