/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomersControllerV1RetrieveRequest = {
  /**
   * The unique identifier of the customer
   */
  customerId?: string | undefined;
  /**
   * The unique email of the customer
   */
  email?: string | undefined;
  xApiKey: string;
};

/** @internal */
export const CustomersControllerV1RetrieveRequest$inboundSchema: z.ZodType<
  CustomersControllerV1RetrieveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string().optional(),
  email: z.string().optional(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type CustomersControllerV1RetrieveRequest$Outbound = {
  customer_id?: string | undefined;
  email?: string | undefined;
  "x-api-key": string;
};

/** @internal */
export const CustomersControllerV1RetrieveRequest$outboundSchema: z.ZodType<
  CustomersControllerV1RetrieveRequest$Outbound,
  z.ZodTypeDef,
  CustomersControllerV1RetrieveRequest
> = z.object({
  customerId: z.string().optional(),
  email: z.string().optional(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomersControllerV1RetrieveRequest$ {
  /** @deprecated use `CustomersControllerV1RetrieveRequest$inboundSchema` instead. */
  export const inboundSchema =
    CustomersControllerV1RetrieveRequest$inboundSchema;
  /** @deprecated use `CustomersControllerV1RetrieveRequest$outboundSchema` instead. */
  export const outboundSchema =
    CustomersControllerV1RetrieveRequest$outboundSchema;
  /** @deprecated use `CustomersControllerV1RetrieveRequest$Outbound` instead. */
  export type Outbound = CustomersControllerV1RetrieveRequest$Outbound;
}

export function customersControllerV1RetrieveRequestToJSON(
  customersControllerV1RetrieveRequest: CustomersControllerV1RetrieveRequest,
): string {
  return JSON.stringify(
    CustomersControllerV1RetrieveRequest$outboundSchema.parse(
      customersControllerV1RetrieveRequest,
    ),
  );
}

export function customersControllerV1RetrieveRequestFromJSON(
  jsonString: string,
): SafeParseResult<CustomersControllerV1RetrieveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CustomersControllerV1RetrieveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomersControllerV1RetrieveRequest' from JSON`,
  );
}
