/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomersBillingControllerV1GenerateRequest = {
  xApiKey: string;
  createCustomerPortalLinkRequestEntity:
    components.CreateCustomerPortalLinkRequestEntity;
};

/** @internal */
export const CustomersBillingControllerV1GenerateRequest$inboundSchema:
  z.ZodType<
    CustomersBillingControllerV1GenerateRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    "x-api-key": z.string(),
    CreateCustomerPortalLinkRequestEntity:
      components.CreateCustomerPortalLinkRequestEntity$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "x-api-key": "xApiKey",
      "CreateCustomerPortalLinkRequestEntity":
        "createCustomerPortalLinkRequestEntity",
    });
  });

/** @internal */
export type CustomersBillingControllerV1GenerateRequest$Outbound = {
  "x-api-key": string;
  CreateCustomerPortalLinkRequestEntity:
    components.CreateCustomerPortalLinkRequestEntity$Outbound;
};

/** @internal */
export const CustomersBillingControllerV1GenerateRequest$outboundSchema:
  z.ZodType<
    CustomersBillingControllerV1GenerateRequest$Outbound,
    z.ZodTypeDef,
    CustomersBillingControllerV1GenerateRequest
  > = z.object({
    xApiKey: z.string(),
    createCustomerPortalLinkRequestEntity:
      components.CreateCustomerPortalLinkRequestEntity$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      xApiKey: "x-api-key",
      createCustomerPortalLinkRequestEntity:
        "CreateCustomerPortalLinkRequestEntity",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomersBillingControllerV1GenerateRequest$ {
  /** @deprecated use `CustomersBillingControllerV1GenerateRequest$inboundSchema` instead. */
  export const inboundSchema =
    CustomersBillingControllerV1GenerateRequest$inboundSchema;
  /** @deprecated use `CustomersBillingControllerV1GenerateRequest$outboundSchema` instead. */
  export const outboundSchema =
    CustomersBillingControllerV1GenerateRequest$outboundSchema;
  /** @deprecated use `CustomersBillingControllerV1GenerateRequest$Outbound` instead. */
  export type Outbound = CustomersBillingControllerV1GenerateRequest$Outbound;
}

export function customersBillingControllerV1GenerateRequestToJSON(
  customersBillingControllerV1GenerateRequest:
    CustomersBillingControllerV1GenerateRequest,
): string {
  return JSON.stringify(
    CustomersBillingControllerV1GenerateRequest$outboundSchema.parse(
      customersBillingControllerV1GenerateRequest,
    ),
  );
}

export function customersBillingControllerV1GenerateRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CustomersBillingControllerV1GenerateRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CustomersBillingControllerV1GenerateRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CustomersBillingControllerV1GenerateRequest' from JSON`,
  );
}
