/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCheckoutRequest = {
  checkoutId: string;
  xApiKey: string;
};

/** @internal */
export const GetCheckoutRequest$inboundSchema: z.ZodType<
  GetCheckoutRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  checkout_id: z.string(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "checkout_id": "checkoutId",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type GetCheckoutRequest$Outbound = {
  checkout_id: string;
  "x-api-key": string;
};

/** @internal */
export const GetCheckoutRequest$outboundSchema: z.ZodType<
  GetCheckoutRequest$Outbound,
  z.ZodTypeDef,
  GetCheckoutRequest
> = z.object({
  checkoutId: z.string(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    checkoutId: "checkout_id",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCheckoutRequest$ {
  /** @deprecated use `GetCheckoutRequest$inboundSchema` instead. */
  export const inboundSchema = GetCheckoutRequest$inboundSchema;
  /** @deprecated use `GetCheckoutRequest$outboundSchema` instead. */
  export const outboundSchema = GetCheckoutRequest$outboundSchema;
  /** @deprecated use `GetCheckoutRequest$Outbound` instead. */
  export type Outbound = GetCheckoutRequest$Outbound;
}

export function getCheckoutRequestToJSON(
  getCheckoutRequest: GetCheckoutRequest,
): string {
  return JSON.stringify(
    GetCheckoutRequest$outboundSchema.parse(getCheckoutRequest),
  );
}

export function getCheckoutRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCheckoutRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCheckoutRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCheckoutRequest' from JSON`,
  );
}
