/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDiscountRequest = {
  /**
   * The unique identifier of the discount (provide either discount_id OR discount_code)
   */
  discountId?: string | undefined;
  /**
   * The unique discount code (provide either discount_id OR discount_code)
   */
  discountCode?: string | undefined;
  xApiKey: string;
};

/** @internal */
export const GetDiscountRequest$inboundSchema: z.ZodType<
  GetDiscountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  discount_id: z.string().optional(),
  discount_code: z.string().optional(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "discount_id": "discountId",
    "discount_code": "discountCode",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type GetDiscountRequest$Outbound = {
  discount_id?: string | undefined;
  discount_code?: string | undefined;
  "x-api-key": string;
};

/** @internal */
export const GetDiscountRequest$outboundSchema: z.ZodType<
  GetDiscountRequest$Outbound,
  z.ZodTypeDef,
  GetDiscountRequest
> = z.object({
  discountId: z.string().optional(),
  discountCode: z.string().optional(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    discountId: "discount_id",
    discountCode: "discount_code",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDiscountRequest$ {
  /** @deprecated use `GetDiscountRequest$inboundSchema` instead. */
  export const inboundSchema = GetDiscountRequest$inboundSchema;
  /** @deprecated use `GetDiscountRequest$outboundSchema` instead. */
  export const outboundSchema = GetDiscountRequest$outboundSchema;
  /** @deprecated use `GetDiscountRequest$Outbound` instead. */
  export type Outbound = GetDiscountRequest$Outbound;
}

export function getDiscountRequestToJSON(
  getDiscountRequest: GetDiscountRequest,
): string {
  return JSON.stringify(
    GetDiscountRequest$outboundSchema.parse(getDiscountRequest),
  );
}

export function getDiscountRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDiscountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDiscountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDiscountRequest' from JSON`,
  );
}
