/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProductRequest = {
  /**
   * The unique identifier of the product
   */
  productId: string;
  xApiKey: string;
};

/** @internal */
export const GetProductRequest$inboundSchema: z.ZodType<
  GetProductRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  product_id: z.string(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "product_id": "productId",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type GetProductRequest$Outbound = {
  product_id: string;
  "x-api-key": string;
};

/** @internal */
export const GetProductRequest$outboundSchema: z.ZodType<
  GetProductRequest$Outbound,
  z.ZodTypeDef,
  GetProductRequest
> = z.object({
  productId: z.string(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    productId: "product_id",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProductRequest$ {
  /** @deprecated use `GetProductRequest$inboundSchema` instead. */
  export const inboundSchema = GetProductRequest$inboundSchema;
  /** @deprecated use `GetProductRequest$outboundSchema` instead. */
  export const outboundSchema = GetProductRequest$outboundSchema;
  /** @deprecated use `GetProductRequest$Outbound` instead. */
  export type Outbound = GetProductRequest$Outbound;
}

export function getProductRequestToJSON(
  getProductRequest: GetProductRequest,
): string {
  return JSON.stringify(
    GetProductRequest$outboundSchema.parse(getProductRequest),
  );
}

export function getProductRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProductRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProductRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProductRequest' from JSON`,
  );
}
