/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSubscriptionRequest = {
  /**
   * The unique identifier of the subscription
   */
  subscriptionId: string;
  xApiKey: string;
};

/** @internal */
export const GetSubscriptionRequest$inboundSchema: z.ZodType<
  GetSubscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  subscription_id: z.string(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "subscription_id": "subscriptionId",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type GetSubscriptionRequest$Outbound = {
  subscription_id: string;
  "x-api-key": string;
};

/** @internal */
export const GetSubscriptionRequest$outboundSchema: z.ZodType<
  GetSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  GetSubscriptionRequest
> = z.object({
  subscriptionId: z.string(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    subscriptionId: "subscription_id",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSubscriptionRequest$ {
  /** @deprecated use `GetSubscriptionRequest$inboundSchema` instead. */
  export const inboundSchema = GetSubscriptionRequest$inboundSchema;
  /** @deprecated use `GetSubscriptionRequest$outboundSchema` instead. */
  export const outboundSchema = GetSubscriptionRequest$outboundSchema;
  /** @deprecated use `GetSubscriptionRequest$Outbound` instead. */
  export type Outbound = GetSubscriptionRequest$Outbound;
}

export function getSubscriptionRequestToJSON(
  getSubscriptionRequest: GetSubscriptionRequest,
): string {
  return JSON.stringify(
    GetSubscriptionRequest$outboundSchema.parse(getSubscriptionRequest),
  );
}

export function getSubscriptionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubscriptionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionRequest' from JSON`,
  );
}
