/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LicensesControllerV1ValidateRequest = {
  xApiKey: string;
  validateLicenseRequestEntity: components.ValidateLicenseRequestEntity;
};

/** @internal */
export const LicensesControllerV1ValidateRequest$inboundSchema: z.ZodType<
  LicensesControllerV1ValidateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "x-api-key": z.string(),
  ValidateLicenseRequestEntity:
    components.ValidateLicenseRequestEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "x-api-key": "xApiKey",
    "ValidateLicenseRequestEntity": "validateLicenseRequestEntity",
  });
});

/** @internal */
export type LicensesControllerV1ValidateRequest$Outbound = {
  "x-api-key": string;
  ValidateLicenseRequestEntity:
    components.ValidateLicenseRequestEntity$Outbound;
};

/** @internal */
export const LicensesControllerV1ValidateRequest$outboundSchema: z.ZodType<
  LicensesControllerV1ValidateRequest$Outbound,
  z.ZodTypeDef,
  LicensesControllerV1ValidateRequest
> = z.object({
  xApiKey: z.string(),
  validateLicenseRequestEntity:
    components.ValidateLicenseRequestEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xApiKey: "x-api-key",
    validateLicenseRequestEntity: "ValidateLicenseRequestEntity",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LicensesControllerV1ValidateRequest$ {
  /** @deprecated use `LicensesControllerV1ValidateRequest$inboundSchema` instead. */
  export const inboundSchema =
    LicensesControllerV1ValidateRequest$inboundSchema;
  /** @deprecated use `LicensesControllerV1ValidateRequest$outboundSchema` instead. */
  export const outboundSchema =
    LicensesControllerV1ValidateRequest$outboundSchema;
  /** @deprecated use `LicensesControllerV1ValidateRequest$Outbound` instead. */
  export type Outbound = LicensesControllerV1ValidateRequest$Outbound;
}

export function licensesControllerV1ValidateRequestToJSON(
  licensesControllerV1ValidateRequest: LicensesControllerV1ValidateRequest,
): string {
  return JSON.stringify(
    LicensesControllerV1ValidateRequest$outboundSchema.parse(
      licensesControllerV1ValidateRequest,
    ),
  );
}

export function licensesControllerV1ValidateRequestFromJSON(
  jsonString: string,
): SafeParseResult<LicensesControllerV1ValidateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LicensesControllerV1ValidateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicensesControllerV1ValidateRequest' from JSON`,
  );
}
