/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ProductsControllerV1SearchRequest = {
  /**
   * The page number
   */
  pageNumber?: number | undefined;
  /**
   * The the page size
   */
  pageSize?: number | undefined;
  xApiKey: string;
};

/** @internal */
export const ProductsControllerV1SearchRequest$inboundSchema: z.ZodType<
  ProductsControllerV1SearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_number: z.number().optional(),
  page_size: z.number().optional(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type ProductsControllerV1SearchRequest$Outbound = {
  page_number?: number | undefined;
  page_size?: number | undefined;
  "x-api-key": string;
};

/** @internal */
export const ProductsControllerV1SearchRequest$outboundSchema: z.ZodType<
  ProductsControllerV1SearchRequest$Outbound,
  z.ZodTypeDef,
  ProductsControllerV1SearchRequest
> = z.object({
  pageNumber: z.number().optional(),
  pageSize: z.number().optional(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductsControllerV1SearchRequest$ {
  /** @deprecated use `ProductsControllerV1SearchRequest$inboundSchema` instead. */
  export const inboundSchema = ProductsControllerV1SearchRequest$inboundSchema;
  /** @deprecated use `ProductsControllerV1SearchRequest$outboundSchema` instead. */
  export const outboundSchema =
    ProductsControllerV1SearchRequest$outboundSchema;
  /** @deprecated use `ProductsControllerV1SearchRequest$Outbound` instead. */
  export type Outbound = ProductsControllerV1SearchRequest$Outbound;
}

export function productsControllerV1SearchRequestToJSON(
  productsControllerV1SearchRequest: ProductsControllerV1SearchRequest,
): string {
  return JSON.stringify(
    ProductsControllerV1SearchRequest$outboundSchema.parse(
      productsControllerV1SearchRequest,
    ),
  );
}

export function productsControllerV1SearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<ProductsControllerV1SearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductsControllerV1SearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductsControllerV1SearchRequest' from JSON`,
  );
}
