/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscriptionsControllerV1RetrieveRequest = {
  /**
   * The unique identifier of the subscription
   */
  subscriptionId: string;
  xApiKey: string;
};

/** @internal */
export const SubscriptionsControllerV1RetrieveRequest$inboundSchema: z.ZodType<
  SubscriptionsControllerV1RetrieveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  subscription_id: z.string(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "subscription_id": "subscriptionId",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type SubscriptionsControllerV1RetrieveRequest$Outbound = {
  subscription_id: string;
  "x-api-key": string;
};

/** @internal */
export const SubscriptionsControllerV1RetrieveRequest$outboundSchema: z.ZodType<
  SubscriptionsControllerV1RetrieveRequest$Outbound,
  z.ZodTypeDef,
  SubscriptionsControllerV1RetrieveRequest
> = z.object({
  subscriptionId: z.string(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    subscriptionId: "subscription_id",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscriptionsControllerV1RetrieveRequest$ {
  /** @deprecated use `SubscriptionsControllerV1RetrieveRequest$inboundSchema` instead. */
  export const inboundSchema =
    SubscriptionsControllerV1RetrieveRequest$inboundSchema;
  /** @deprecated use `SubscriptionsControllerV1RetrieveRequest$outboundSchema` instead. */
  export const outboundSchema =
    SubscriptionsControllerV1RetrieveRequest$outboundSchema;
  /** @deprecated use `SubscriptionsControllerV1RetrieveRequest$Outbound` instead. */
  export type Outbound = SubscriptionsControllerV1RetrieveRequest$Outbound;
}

export function subscriptionsControllerV1RetrieveRequestToJSON(
  subscriptionsControllerV1RetrieveRequest:
    SubscriptionsControllerV1RetrieveRequest,
): string {
  return JSON.stringify(
    SubscriptionsControllerV1RetrieveRequest$outboundSchema.parse(
      subscriptionsControllerV1RetrieveRequest,
    ),
  );
}

export function subscriptionsControllerV1RetrieveRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscriptionsControllerV1RetrieveRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscriptionsControllerV1RetrieveRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscriptionsControllerV1RetrieveRequest' from JSON`,
  );
}
