/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TransactionsControllerV1SearchRequest = {
  /**
   * The customer id
   */
  customerId?: string | undefined;
  /**
   * The order id
   */
  orderId?: string | undefined;
  /**
   * The product id
   */
  productId?: string | undefined;
  /**
   * The page number
   */
  pageNumber?: number | undefined;
  /**
   * The the page size
   */
  pageSize?: number | undefined;
  xApiKey: string;
};

/** @internal */
export const TransactionsControllerV1SearchRequest$inboundSchema: z.ZodType<
  TransactionsControllerV1SearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string().optional(),
  order_id: z.string().optional(),
  product_id: z.string().optional(),
  page_number: z.number().optional(),
  page_size: z.number().optional(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "order_id": "orderId",
    "product_id": "productId",
    "page_number": "pageNumber",
    "page_size": "pageSize",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type TransactionsControllerV1SearchRequest$Outbound = {
  customer_id?: string | undefined;
  order_id?: string | undefined;
  product_id?: string | undefined;
  page_number?: number | undefined;
  page_size?: number | undefined;
  "x-api-key": string;
};

/** @internal */
export const TransactionsControllerV1SearchRequest$outboundSchema: z.ZodType<
  TransactionsControllerV1SearchRequest$Outbound,
  z.ZodTypeDef,
  TransactionsControllerV1SearchRequest
> = z.object({
  customerId: z.string().optional(),
  orderId: z.string().optional(),
  productId: z.string().optional(),
  pageNumber: z.number().optional(),
  pageSize: z.number().optional(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    orderId: "order_id",
    productId: "product_id",
    pageNumber: "page_number",
    pageSize: "page_size",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransactionsControllerV1SearchRequest$ {
  /** @deprecated use `TransactionsControllerV1SearchRequest$inboundSchema` instead. */
  export const inboundSchema =
    TransactionsControllerV1SearchRequest$inboundSchema;
  /** @deprecated use `TransactionsControllerV1SearchRequest$outboundSchema` instead. */
  export const outboundSchema =
    TransactionsControllerV1SearchRequest$outboundSchema;
  /** @deprecated use `TransactionsControllerV1SearchRequest$Outbound` instead. */
  export type Outbound = TransactionsControllerV1SearchRequest$Outbound;
}

export function transactionsControllerV1SearchRequestToJSON(
  transactionsControllerV1SearchRequest: TransactionsControllerV1SearchRequest,
): string {
  return JSON.stringify(
    TransactionsControllerV1SearchRequest$outboundSchema.parse(
      transactionsControllerV1SearchRequest,
    ),
  );
}

export function transactionsControllerV1SearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<TransactionsControllerV1SearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TransactionsControllerV1SearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionsControllerV1SearchRequest' from JSON`,
  );
}
