/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MetadataEntity = {};

/** @internal */
export const MetadataEntity$inboundSchema: z.ZodType<
  MetadataEntity,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type MetadataEntity$Outbound = {};

/** @internal */
export const MetadataEntity$outboundSchema: z.ZodType<
  MetadataEntity$Outbound,
  z.ZodTypeDef,
  MetadataEntity
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MetadataEntity$ {
  /** @deprecated use `MetadataEntity$inboundSchema` instead. */
  export const inboundSchema = MetadataEntity$inboundSchema;
  /** @deprecated use `MetadataEntity$outboundSchema` instead. */
  export const outboundSchema = MetadataEntity$outboundSchema;
  /** @deprecated use `MetadataEntity$Outbound` instead. */
  export type Outbound = MetadataEntity$Outbound;
}

export function metadataEntityToJSON(metadataEntity: MetadataEntity): string {
  return JSON.stringify(MetadataEntity$outboundSchema.parse(metadataEntity));
}

export function metadataEntityFromJSON(
  jsonString: string,
): SafeParseResult<MetadataEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetadataEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetadataEntity' from JSON`,
  );
}
