/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomField,
  CustomField$inboundSchema,
  CustomField$Outbound,
  CustomField$outboundSchema,
} from "./customfield.js";
import {
  MetadataEntity,
  MetadataEntity$inboundSchema,
  MetadataEntity$Outbound,
  MetadataEntity$outboundSchema,
} from "./metadataentity.js";
import {
  OrderEntity,
  OrderEntity$inboundSchema,
  OrderEntity$Outbound,
  OrderEntity$outboundSchema,
} from "./orderentity.js";
import {
  ProductFeatureEntity,
  ProductFeatureEntity$inboundSchema,
  ProductFeatureEntity$Outbound,
  ProductFeatureEntity$outboundSchema,
} from "./productfeatureentity.js";

/**
 * String representing the environment.
 */
export const CheckoutEntityMode = {
  Test: "test",
  Live: "live",
  Sandbox: "sandbox",
} as const;
/**
 * String representing the environment.
 */
export type CheckoutEntityMode = ClosedEnum<typeof CheckoutEntityMode>;

/**
 * The subscription associated with the checkout session.
 */
export type Subscription = {};

/**
 * The customer associated with the checkout session.
 */
export type CheckoutEntityCustomer = {};

export type CheckoutEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: CheckoutEntityMode;
  /**
   * String representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * Status of the checkout.
   */
  status: string;
  /**
   * Identify and track each checkout request.
   */
  requestId?: string | undefined;
  /**
   * The product associated with the checkout session.
   */
  product: Array<string>;
  /**
   * The number of units for the of the product.
   */
  units?: number | undefined;
  /**
   * The order associated with the checkout session.
   */
  order?: OrderEntity | undefined;
  /**
   * The subscription associated with the checkout session.
   */
  subscription?: Subscription | undefined;
  /**
   * The customer associated with the checkout session.
   */
  customer?: CheckoutEntityCustomer | undefined;
  /**
   * Additional information collected from your customer during the checkout process.
   */
  customFields?: Array<CustomField> | undefined;
  /**
   * The URL to which the customer will be redirected to complete the payment.
   */
  checkoutUrl: string;
  /**
   * The URL to which the user will be redirected after the checkout process is completed.
   */
  successUrl: string;
  /**
   * Features issued for the order.
   */
  feature?: Array<ProductFeatureEntity> | undefined;
  /**
   * A key-value pair where the key is a string, and the value can be a string, number, or null.
   */
  metadata?: Array<MetadataEntity> | undefined;
};

/** @internal */
export const CheckoutEntityMode$inboundSchema: z.ZodNativeEnum<
  typeof CheckoutEntityMode
> = z.nativeEnum(CheckoutEntityMode);

/** @internal */
export const CheckoutEntityMode$outboundSchema: z.ZodNativeEnum<
  typeof CheckoutEntityMode
> = CheckoutEntityMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutEntityMode$ {
  /** @deprecated use `CheckoutEntityMode$inboundSchema` instead. */
  export const inboundSchema = CheckoutEntityMode$inboundSchema;
  /** @deprecated use `CheckoutEntityMode$outboundSchema` instead. */
  export const outboundSchema = CheckoutEntityMode$outboundSchema;
}

/** @internal */
export const Subscription$inboundSchema: z.ZodType<
  Subscription,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type Subscription$Outbound = {};

/** @internal */
export const Subscription$outboundSchema: z.ZodType<
  Subscription$Outbound,
  z.ZodTypeDef,
  Subscription
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Subscription$ {
  /** @deprecated use `Subscription$inboundSchema` instead. */
  export const inboundSchema = Subscription$inboundSchema;
  /** @deprecated use `Subscription$outboundSchema` instead. */
  export const outboundSchema = Subscription$outboundSchema;
  /** @deprecated use `Subscription$Outbound` instead. */
  export type Outbound = Subscription$Outbound;
}

export function subscriptionToJSON(subscription: Subscription): string {
  return JSON.stringify(Subscription$outboundSchema.parse(subscription));
}

export function subscriptionFromJSON(
  jsonString: string,
): SafeParseResult<Subscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subscription' from JSON`,
  );
}

/** @internal */
export const CheckoutEntityCustomer$inboundSchema: z.ZodType<
  CheckoutEntityCustomer,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type CheckoutEntityCustomer$Outbound = {};

/** @internal */
export const CheckoutEntityCustomer$outboundSchema: z.ZodType<
  CheckoutEntityCustomer$Outbound,
  z.ZodTypeDef,
  CheckoutEntityCustomer
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutEntityCustomer$ {
  /** @deprecated use `CheckoutEntityCustomer$inboundSchema` instead. */
  export const inboundSchema = CheckoutEntityCustomer$inboundSchema;
  /** @deprecated use `CheckoutEntityCustomer$outboundSchema` instead. */
  export const outboundSchema = CheckoutEntityCustomer$outboundSchema;
  /** @deprecated use `CheckoutEntityCustomer$Outbound` instead. */
  export type Outbound = CheckoutEntityCustomer$Outbound;
}

export function checkoutEntityCustomerToJSON(
  checkoutEntityCustomer: CheckoutEntityCustomer,
): string {
  return JSON.stringify(
    CheckoutEntityCustomer$outboundSchema.parse(checkoutEntityCustomer),
  );
}

export function checkoutEntityCustomerFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutEntityCustomer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckoutEntityCustomer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutEntityCustomer' from JSON`,
  );
}

/** @internal */
export const CheckoutEntity$inboundSchema: z.ZodType<
  CheckoutEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: CheckoutEntityMode$inboundSchema,
  object: z.string(),
  status: z.string(),
  request_id: z.string().optional(),
  product: z.array(z.string()),
  units: z.number().optional(),
  order: OrderEntity$inboundSchema.optional(),
  subscription: z.lazy(() => Subscription$inboundSchema).optional(),
  customer: z.lazy(() => CheckoutEntityCustomer$inboundSchema).optional(),
  custom_fields: z.array(CustomField$inboundSchema).optional(),
  checkout_url: z.string(),
  success_url: z.string(),
  feature: z.array(ProductFeatureEntity$inboundSchema).optional(),
  metadata: z.array(MetadataEntity$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "custom_fields": "customFields",
    "checkout_url": "checkoutUrl",
    "success_url": "successUrl",
  });
});

/** @internal */
export type CheckoutEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  status: string;
  request_id?: string | undefined;
  product: Array<string>;
  units?: number | undefined;
  order?: OrderEntity$Outbound | undefined;
  subscription?: Subscription$Outbound | undefined;
  customer?: CheckoutEntityCustomer$Outbound | undefined;
  custom_fields?: Array<CustomField$Outbound> | undefined;
  checkout_url: string;
  success_url: string;
  feature?: Array<ProductFeatureEntity$Outbound> | undefined;
  metadata?: Array<MetadataEntity$Outbound> | undefined;
};

/** @internal */
export const CheckoutEntity$outboundSchema: z.ZodType<
  CheckoutEntity$Outbound,
  z.ZodTypeDef,
  CheckoutEntity
> = z.object({
  id: z.string(),
  mode: CheckoutEntityMode$outboundSchema,
  object: z.string(),
  status: z.string(),
  requestId: z.string().optional(),
  product: z.array(z.string()),
  units: z.number().optional(),
  order: OrderEntity$outboundSchema.optional(),
  subscription: z.lazy(() => Subscription$outboundSchema).optional(),
  customer: z.lazy(() => CheckoutEntityCustomer$outboundSchema).optional(),
  customFields: z.array(CustomField$outboundSchema).optional(),
  checkoutUrl: z.string(),
  successUrl: z.string(),
  feature: z.array(ProductFeatureEntity$outboundSchema).optional(),
  metadata: z.array(MetadataEntity$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    customFields: "custom_fields",
    checkoutUrl: "checkout_url",
    successUrl: "success_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutEntity$ {
  /** @deprecated use `CheckoutEntity$inboundSchema` instead. */
  export const inboundSchema = CheckoutEntity$inboundSchema;
  /** @deprecated use `CheckoutEntity$outboundSchema` instead. */
  export const outboundSchema = CheckoutEntity$outboundSchema;
  /** @deprecated use `CheckoutEntity$Outbound` instead. */
  export type Outbound = CheckoutEntity$Outbound;
}

export function checkoutEntityToJSON(checkoutEntity: CheckoutEntity): string {
  return JSON.stringify(CheckoutEntity$outboundSchema.parse(checkoutEntity));
}

export function checkoutEntityFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckoutEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutEntity' from JSON`,
  );
}
