/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * String representing the environment.
 */
export const DiscountEntityMode = {
  Test: "test",
  Live: "live",
  Sandbox: "sandbox",
} as const;
/**
 * String representing the environment.
 */
export type DiscountEntityMode = ClosedEnum<typeof DiscountEntityMode>;

/**
 * The status of the discount (e.g., active, inactive).
 */
export const DiscountEntityStatus = {
  Active: "active",
  Draft: "draft",
  Expired: "expired",
  Scheduled: "scheduled",
} as const;
/**
 * The status of the discount (e.g., active, inactive).
 */
export type DiscountEntityStatus = ClosedEnum<typeof DiscountEntityStatus>;

/**
 * The type of the discount, either "percentage" or "fixed".
 */
export const DiscountEntityType = {
  Percentage: "percentage",
  Fixed: "fixed",
} as const;
/**
 * The type of the discount, either "percentage" or "fixed".
 */
export type DiscountEntityType = ClosedEnum<typeof DiscountEntityType>;

/**
 * The maximum number of redemptions allowed for the discount.
 */
export type MaxRedemptions = {};

/**
 * The duration type for the discount.
 */
export const Duration = {
  Forever: "forever",
  Once: "once",
  Repeating: "repeating",
} as const;
/**
 * The duration type for the discount.
 */
export type Duration = ClosedEnum<typeof Duration>;

/**
 * The number of months the discount is valid for. Only applicable if the duration is "repeating" and the product is a subscription.
 */
export type DurationInMonths = {};

export type DiscountEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: DiscountEntityMode;
  /**
   * A string representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The status of the discount (e.g., active, inactive).
   */
  status: DiscountEntityStatus;
  /**
   * The name of the discount.
   */
  name: string;
  /**
   * The discount code. A unique identifier for the discount.
   */
  code: string;
  /**
   * The type of the discount, either "percentage" or "fixed".
   */
  type: DiscountEntityType;
  /**
   * The amount of the discount. Can be a percentage or a fixed amount.
   */
  amount: number;
  /**
   * The percentage of the discount. Only applicable if type is "percentage".
   */
  percentage?: number | undefined;
  /**
   * The expiry date of the discount.
   */
  expiryDate?: Date | undefined;
  /**
   * The maximum number of redemptions allowed for the discount.
   */
  maxRedemptions?: MaxRedemptions | undefined;
  /**
   * The duration type for the discount.
   */
  duration?: Duration | undefined;
  /**
   * The number of months the discount is valid for. Only applicable if the duration is "repeating" and the product is a subscription.
   */
  durationInMonths?: DurationInMonths | undefined;
  /**
   * The list of product IDs to which this discount applies.
   */
  appliesToProducts?: Array<string> | undefined;
};

/** @internal */
export const DiscountEntityMode$inboundSchema: z.ZodNativeEnum<
  typeof DiscountEntityMode
> = z.nativeEnum(DiscountEntityMode);

/** @internal */
export const DiscountEntityMode$outboundSchema: z.ZodNativeEnum<
  typeof DiscountEntityMode
> = DiscountEntityMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountEntityMode$ {
  /** @deprecated use `DiscountEntityMode$inboundSchema` instead. */
  export const inboundSchema = DiscountEntityMode$inboundSchema;
  /** @deprecated use `DiscountEntityMode$outboundSchema` instead. */
  export const outboundSchema = DiscountEntityMode$outboundSchema;
}

/** @internal */
export const DiscountEntityStatus$inboundSchema: z.ZodNativeEnum<
  typeof DiscountEntityStatus
> = z.nativeEnum(DiscountEntityStatus);

/** @internal */
export const DiscountEntityStatus$outboundSchema: z.ZodNativeEnum<
  typeof DiscountEntityStatus
> = DiscountEntityStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountEntityStatus$ {
  /** @deprecated use `DiscountEntityStatus$inboundSchema` instead. */
  export const inboundSchema = DiscountEntityStatus$inboundSchema;
  /** @deprecated use `DiscountEntityStatus$outboundSchema` instead. */
  export const outboundSchema = DiscountEntityStatus$outboundSchema;
}

/** @internal */
export const DiscountEntityType$inboundSchema: z.ZodNativeEnum<
  typeof DiscountEntityType
> = z.nativeEnum(DiscountEntityType);

/** @internal */
export const DiscountEntityType$outboundSchema: z.ZodNativeEnum<
  typeof DiscountEntityType
> = DiscountEntityType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountEntityType$ {
  /** @deprecated use `DiscountEntityType$inboundSchema` instead. */
  export const inboundSchema = DiscountEntityType$inboundSchema;
  /** @deprecated use `DiscountEntityType$outboundSchema` instead. */
  export const outboundSchema = DiscountEntityType$outboundSchema;
}

/** @internal */
export const MaxRedemptions$inboundSchema: z.ZodType<
  MaxRedemptions,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type MaxRedemptions$Outbound = {};

/** @internal */
export const MaxRedemptions$outboundSchema: z.ZodType<
  MaxRedemptions$Outbound,
  z.ZodTypeDef,
  MaxRedemptions
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MaxRedemptions$ {
  /** @deprecated use `MaxRedemptions$inboundSchema` instead. */
  export const inboundSchema = MaxRedemptions$inboundSchema;
  /** @deprecated use `MaxRedemptions$outboundSchema` instead. */
  export const outboundSchema = MaxRedemptions$outboundSchema;
  /** @deprecated use `MaxRedemptions$Outbound` instead. */
  export type Outbound = MaxRedemptions$Outbound;
}

export function maxRedemptionsToJSON(maxRedemptions: MaxRedemptions): string {
  return JSON.stringify(MaxRedemptions$outboundSchema.parse(maxRedemptions));
}

export function maxRedemptionsFromJSON(
  jsonString: string,
): SafeParseResult<MaxRedemptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MaxRedemptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MaxRedemptions' from JSON`,
  );
}

/** @internal */
export const Duration$inboundSchema: z.ZodNativeEnum<typeof Duration> = z
  .nativeEnum(Duration);

/** @internal */
export const Duration$outboundSchema: z.ZodNativeEnum<typeof Duration> =
  Duration$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Duration$ {
  /** @deprecated use `Duration$inboundSchema` instead. */
  export const inboundSchema = Duration$inboundSchema;
  /** @deprecated use `Duration$outboundSchema` instead. */
  export const outboundSchema = Duration$outboundSchema;
}

/** @internal */
export const DurationInMonths$inboundSchema: z.ZodType<
  DurationInMonths,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type DurationInMonths$Outbound = {};

/** @internal */
export const DurationInMonths$outboundSchema: z.ZodType<
  DurationInMonths$Outbound,
  z.ZodTypeDef,
  DurationInMonths
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DurationInMonths$ {
  /** @deprecated use `DurationInMonths$inboundSchema` instead. */
  export const inboundSchema = DurationInMonths$inboundSchema;
  /** @deprecated use `DurationInMonths$outboundSchema` instead. */
  export const outboundSchema = DurationInMonths$outboundSchema;
  /** @deprecated use `DurationInMonths$Outbound` instead. */
  export type Outbound = DurationInMonths$Outbound;
}

export function durationInMonthsToJSON(
  durationInMonths: DurationInMonths,
): string {
  return JSON.stringify(
    DurationInMonths$outboundSchema.parse(durationInMonths),
  );
}

export function durationInMonthsFromJSON(
  jsonString: string,
): SafeParseResult<DurationInMonths, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DurationInMonths$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DurationInMonths' from JSON`,
  );
}

/** @internal */
export const DiscountEntity$inboundSchema: z.ZodType<
  DiscountEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: DiscountEntityMode$inboundSchema,
  object: z.string(),
  status: DiscountEntityStatus$inboundSchema,
  name: z.string(),
  code: z.string(),
  type: DiscountEntityType$inboundSchema,
  amount: z.number(),
  percentage: z.number().optional(),
  expiry_date: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  max_redemptions: z.lazy(() => MaxRedemptions$inboundSchema).optional(),
  duration: Duration$inboundSchema.optional(),
  duration_in_months: z.lazy(() => DurationInMonths$inboundSchema).optional(),
  applies_to_products: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "expiry_date": "expiryDate",
    "max_redemptions": "maxRedemptions",
    "duration_in_months": "durationInMonths",
    "applies_to_products": "appliesToProducts",
  });
});

/** @internal */
export type DiscountEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  status: string;
  name: string;
  code: string;
  type: string;
  amount: number;
  percentage?: number | undefined;
  expiry_date?: string | undefined;
  max_redemptions?: MaxRedemptions$Outbound | undefined;
  duration?: string | undefined;
  duration_in_months?: DurationInMonths$Outbound | undefined;
  applies_to_products?: Array<string> | undefined;
};

/** @internal */
export const DiscountEntity$outboundSchema: z.ZodType<
  DiscountEntity$Outbound,
  z.ZodTypeDef,
  DiscountEntity
> = z.object({
  id: z.string(),
  mode: DiscountEntityMode$outboundSchema,
  object: z.string(),
  status: DiscountEntityStatus$outboundSchema,
  name: z.string(),
  code: z.string(),
  type: DiscountEntityType$outboundSchema,
  amount: z.number(),
  percentage: z.number().optional(),
  expiryDate: z.date().transform(v => v.toISOString()).optional(),
  maxRedemptions: z.lazy(() => MaxRedemptions$outboundSchema).optional(),
  duration: Duration$outboundSchema.optional(),
  durationInMonths: z.lazy(() => DurationInMonths$outboundSchema).optional(),
  appliesToProducts: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    expiryDate: "expiry_date",
    maxRedemptions: "max_redemptions",
    durationInMonths: "duration_in_months",
    appliesToProducts: "applies_to_products",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountEntity$ {
  /** @deprecated use `DiscountEntity$inboundSchema` instead. */
  export const inboundSchema = DiscountEntity$inboundSchema;
  /** @deprecated use `DiscountEntity$outboundSchema` instead. */
  export const outboundSchema = DiscountEntity$outboundSchema;
  /** @deprecated use `DiscountEntity$Outbound` instead. */
  export type Outbound = DiscountEntity$Outbound;
}

export function discountEntityToJSON(discountEntity: DiscountEntity): string {
  return JSON.stringify(DiscountEntity$outboundSchema.parse(discountEntity));
}

export function discountEntityFromJSON(
  jsonString: string,
): SafeParseResult<DiscountEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiscountEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiscountEntity' from JSON`,
  );
}
