/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DiscountsControllerV1RetrieveRequest = {
  /**
   * The unique identifier of the discount (provide either discount_id OR discount_code)
   */
  discountId?: string | undefined;
  /**
   * The unique discount code (provide either discount_id OR discount_code)
   */
  discountCode?: string | undefined;
  xApiKey: string;
};

/** @internal */
export const DiscountsControllerV1RetrieveRequest$inboundSchema: z.ZodType<
  DiscountsControllerV1RetrieveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  discount_id: z.string().optional(),
  discount_code: z.string().optional(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "discount_id": "discountId",
    "discount_code": "discountCode",
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type DiscountsControllerV1RetrieveRequest$Outbound = {
  discount_id?: string | undefined;
  discount_code?: string | undefined;
  "x-api-key": string;
};

/** @internal */
export const DiscountsControllerV1RetrieveRequest$outboundSchema: z.ZodType<
  DiscountsControllerV1RetrieveRequest$Outbound,
  z.ZodTypeDef,
  DiscountsControllerV1RetrieveRequest
> = z.object({
  discountId: z.string().optional(),
  discountCode: z.string().optional(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    discountId: "discount_id",
    discountCode: "discount_code",
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DiscountsControllerV1RetrieveRequest$ {
  /** @deprecated use `DiscountsControllerV1RetrieveRequest$inboundSchema` instead. */
  export const inboundSchema =
    DiscountsControllerV1RetrieveRequest$inboundSchema;
  /** @deprecated use `DiscountsControllerV1RetrieveRequest$outboundSchema` instead. */
  export const outboundSchema =
    DiscountsControllerV1RetrieveRequest$outboundSchema;
  /** @deprecated use `DiscountsControllerV1RetrieveRequest$Outbound` instead. */
  export type Outbound = DiscountsControllerV1RetrieveRequest$Outbound;
}

export function discountsControllerV1RetrieveRequestToJSON(
  discountsControllerV1RetrieveRequest: DiscountsControllerV1RetrieveRequest,
): string {
  return JSON.stringify(
    DiscountsControllerV1RetrieveRequest$outboundSchema.parse(
      discountsControllerV1RetrieveRequest,
    ),
  );
}

export function discountsControllerV1RetrieveRequestFromJSON(
  jsonString: string,
): SafeParseResult<DiscountsControllerV1RetrieveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DiscountsControllerV1RetrieveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiscountsControllerV1RetrieveRequest' from JSON`,
  );
}
