/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LicensesControllerV1DeactivateRequest = {
  xApiKey: string;
  deactivateLicenseRequestEntity: components.DeactivateLicenseRequestEntity;
};

/** @internal */
export const LicensesControllerV1DeactivateRequest$inboundSchema: z.ZodType<
  LicensesControllerV1DeactivateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "x-api-key": z.string(),
  DeactivateLicenseRequestEntity:
    components.DeactivateLicenseRequestEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "x-api-key": "xApiKey",
    "DeactivateLicenseRequestEntity": "deactivateLicenseRequestEntity",
  });
});

/** @internal */
export type LicensesControllerV1DeactivateRequest$Outbound = {
  "x-api-key": string;
  DeactivateLicenseRequestEntity:
    components.DeactivateLicenseRequestEntity$Outbound;
};

/** @internal */
export const LicensesControllerV1DeactivateRequest$outboundSchema: z.ZodType<
  LicensesControllerV1DeactivateRequest$Outbound,
  z.ZodTypeDef,
  LicensesControllerV1DeactivateRequest
> = z.object({
  xApiKey: z.string(),
  deactivateLicenseRequestEntity:
    components.DeactivateLicenseRequestEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xApiKey: "x-api-key",
    deactivateLicenseRequestEntity: "DeactivateLicenseRequestEntity",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LicensesControllerV1DeactivateRequest$ {
  /** @deprecated use `LicensesControllerV1DeactivateRequest$inboundSchema` instead. */
  export const inboundSchema =
    LicensesControllerV1DeactivateRequest$inboundSchema;
  /** @deprecated use `LicensesControllerV1DeactivateRequest$outboundSchema` instead. */
  export const outboundSchema =
    LicensesControllerV1DeactivateRequest$outboundSchema;
  /** @deprecated use `LicensesControllerV1DeactivateRequest$Outbound` instead. */
  export type Outbound = LicensesControllerV1DeactivateRequest$Outbound;
}

export function licensesControllerV1DeactivateRequestToJSON(
  licensesControllerV1DeactivateRequest: LicensesControllerV1DeactivateRequest,
): string {
  return JSON.stringify(
    LicensesControllerV1DeactivateRequest$outboundSchema.parse(
      licensesControllerV1DeactivateRequest,
    ),
  );
}

export function licensesControllerV1DeactivateRequestFromJSON(
  jsonString: string,
): SafeParseResult<LicensesControllerV1DeactivateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      LicensesControllerV1DeactivateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicensesControllerV1DeactivateRequest' from JSON`,
  );
}
