/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscriptionsControllerV1CancelRequest = {
  id: string;
  xApiKey: string;
};

/** @internal */
export const SubscriptionsControllerV1CancelRequest$inboundSchema: z.ZodType<
  SubscriptionsControllerV1CancelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  "x-api-key": z.string(),
}).transform((v) => {
  return remap$(v, {
    "x-api-key": "xApiKey",
  });
});

/** @internal */
export type SubscriptionsControllerV1CancelRequest$Outbound = {
  id: string;
  "x-api-key": string;
};

/** @internal */
export const SubscriptionsControllerV1CancelRequest$outboundSchema: z.ZodType<
  SubscriptionsControllerV1CancelRequest$Outbound,
  z.ZodTypeDef,
  SubscriptionsControllerV1CancelRequest
> = z.object({
  id: z.string(),
  xApiKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    xApiKey: "x-api-key",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscriptionsControllerV1CancelRequest$ {
  /** @deprecated use `SubscriptionsControllerV1CancelRequest$inboundSchema` instead. */
  export const inboundSchema =
    SubscriptionsControllerV1CancelRequest$inboundSchema;
  /** @deprecated use `SubscriptionsControllerV1CancelRequest$outboundSchema` instead. */
  export const outboundSchema =
    SubscriptionsControllerV1CancelRequest$outboundSchema;
  /** @deprecated use `SubscriptionsControllerV1CancelRequest$Outbound` instead. */
  export type Outbound = SubscriptionsControllerV1CancelRequest$Outbound;
}

export function subscriptionsControllerV1CancelRequestToJSON(
  subscriptionsControllerV1CancelRequest:
    SubscriptionsControllerV1CancelRequest,
): string {
  return JSON.stringify(
    SubscriptionsControllerV1CancelRequest$outboundSchema.parse(
      subscriptionsControllerV1CancelRequest,
    ),
  );
}

export function subscriptionsControllerV1CancelRequestFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionsControllerV1CancelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SubscriptionsControllerV1CancelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionsControllerV1CancelRequest' from JSON`,
  );
}
